trigger:
  branches:
    include:
      - main
pr: none

name: Deploy Azure Static Web App

variables:
- group: chatbot_variables
- name: vmImageName
  value: 'ubuntu-latest'

pool:
  vmImage: $(vmImageName)

steps:
- task: AzureStaticWebApp@0
  displayName: 'Deploy WebApp'
  inputs:
    app_location: '.'
    output_location: 'dist/my-resume-chatbot/browser'
    api_location: 'api/src'
    azure_static_web_apps_api_token: $(deployment_token)